1)

Python library is a collection of pre-written code and functionalities that can be used by Python developers to perform specific tasks without having to write the code from scratch. These libraries typically contain modules, classes, and functions that address common programming challenges, making it easier for developers to build applications by leveraging existing solutions.

Python libraries have several purpose like :-

1) Code Reusability

2)code stabilazation

3)Time efficiency

4)Modularity

5)Community contributions




In [1]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Print the array
print("Array:")
print(my_array)

# Get the shape, size, and dimensions
shape = my_array.shape
size = my_array.size
dimensions = my_array.ndim

# Print the results
print("\nShape:", shape)
print("Size:", size)
print("Dimensions:", dimensions)


Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Size: 12
Dimensions: 2


In [3]:


# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Access the first row
first_row = my_array[0, :]

# Print the result
print("First Row:")
print(first_row)


First Row:
[1 2 3 4]


In [4]:
# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = my_array[2, 3]

# Print the result
print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


In [5]:
# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = my_array[:, 1::2]

# Print the result
print("All odd-indexed elements:")
print(odd_indexed_elements)


All odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [6]:
# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

# Print the result
print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)


Random 3x3 matrix with values between 0 and 1:
[[0.34013658 0.20646523 0.26792445]
 [0.63745769 0.39279937 0.59521218]
 [0.24264488 0.89201248 0.02188258]]


1) np.random.rand:

This function generates random values from a uniform distribution over the interval [0, 1).

The generated values are floats and are uniformly distributed between 0 (inclusive) and 1 (exclusive).

You can specify the shape of the output array by passing the desired dimensions as arguments.

2) np.random.randn:

This function generates random values from a standard normal distribution (mean = 0, standard deviation = 1).

The generated values are floats and are sampled from a standard normal distribution.

You can also specify the shape of the output array by passing the desired dimensions as arguments

In [7]:
# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Add a new axis using np.newaxis
new_dimension_array = original_array[:, :, np.newaxis]

# Alternatively, you can use np.expand_dims
# new_dimension_array = np.expand_dims(original_array, axis=2)

# Print the result
print("Original Array:")
print(original_array)

print("\nArray with Increased Dimension:")
print(new_dimension_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with Increased Dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [8]:
# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Transpose the array using .T attribute
transposed_array_t = original_array.T

# Transpose the array using np.transpose()
transposed_array_np = np.transpose(original_array)

# Print the results
print("Original Array:")
print(original_array)

print("\nTransposed Array (using .T):")
print(transposed_array_t)

print("\nTransposed Array (using np.transpose()):")
print(transposed_array_np)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array (using .T):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Transposed Array (using np.transpose()):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [9]:
# Define matrices A and B
matrix_A = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

matrix_B = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Addition
addition_result = matrix_A + matrix_B

# Matrix Multiplication
multiplication_result = np.dot(matrix_A, matrix_B.T)  # Transpose of B for proper multiplication

# Subtraction
subtraction_result = matrix_A - matrix_B

# Division (element-wise)
division_result = np.divide(matrix_B, matrix_A)

# Print the results
print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nAddition Result:")
print(addition_result)

print("\nMatrix Multiplication Result:")
print(multiplication_result)

print("\nSubtraction Result:")
print(subtraction_result)

print("\nDivision Result:")
print(division_result)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Addition Result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Multiplication Result:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Subtraction Result:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division Result:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**np.linalg.inv function:**

The np.linalg.inv function is used to compute the inverse of a matrix. If A is a square matrix, then np.linalg.inv(A) returns the inverse of matrix A.

The significance of this function is mainly in solving linear systems of equations, as finding the inverse is one way to solve a system of linear equations.

**Broadcasting in NumPy:**

Broadcasting is a powerful feature in NumPy that allows arrays of different shapes and sizes to be combined and operated on together.

When performing element-wise operations, NumPy automatically broadcasts the smaller array to the shape of the larger one.

Broadcasting rules allow for operations between arrays of different shapes without explicitly reshaping them.

**np.ndarray.byteswap function:**

The np.ndarray.byteswap function can be used to swap the byte order of an array. It allows you to change the endianness of the data in the array.